name: Build

on:
  pull_request:
    branches:
      - 'future'
    paths-ignore:
      - '.gitignore'
      - 'examples'
      - 'README.md'

jobs:
  build:
    name: ${{ matrix.os }}-${{ matrix.jdk }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        jdk: [ 11, 17 ]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: yersan/wildfly-installation-manager-api
          path: wildfly-installation-manager-api
          ref: integration-wip
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: spyrkob/wildfly-channel
          path: wildfly-channel
          ref: manifest
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adopt'
          cache: maven
      - name: Build manager API
        run: cd wildfly-installation-manager-api && mvn clean install -DskipTests
      - name: Build wildfly-channel
        run: cd wildfly-channel && mvn clean install -DskipTests
      - name: Build and test
        run: mvn clean install -DallTests -Pdist
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: surefire-reports
          path: '**/surefire-reports/*.txt'
